project:
  type: book
  output-dir: ../docs
  
book:
  title: "Databrary Analytics"
  author: ["Rick Gilmore", "Andrea Seisler"]
  cover-image: "include/img/databrary-new-leaf.jpg"
  chapters:
    - index.qmd
    - weekly.qmd
    # - institutions-investigators.qmd
    # - tags-keywords.qmd
    # - funders.qmd
    # - assets.qmd
    # - demographics.qmd
    # - shared-volumes.qmd
    # - workflow.qmd
  repo-url: https://github.com/databrary/analytics
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    number-sections: false
    date-modified: last-modified
    date: today
    fontsize: 1.2em
    code-fold: true
    
knitr:
  opts_chunk:
    fig.path: include/fig/